/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.1.2'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Technical Conference
 * Environment: Production
 * Id: 39604f33-8001-00aa-4724-192a93745c77
 *
 * -------------------------------------------------------------------------------
 */

import type { LanguageCodenames } from "../system/languages.generated.ts";

/*
 * Type representing codename of 'Czech' language
 */
export type CzechLanguageCodename = keyof Pick<Record<LanguageCodenames, null>, "cs">;

/*
 * Typeguard for codename of 'Czech' language
 */
export function isCzechLanguageCodename(value: string | undefined | null): value is CzechLanguageCodename {
  return typeof value === "string" && value === ("cs" satisfies CzechLanguageCodename);
}
