/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.1.2'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Technical Conference
 * Environment: Production
 * Id: 39604f33-8001-00aa-4724-192a93745c77
 *
 * -------------------------------------------------------------------------------
 */

import type { LanguageCodenames } from "../system/languages.generated.ts";

/*
 * Type representing codename of 'Default project language' language
 */
export type DefaultProjectLanguageLanguageCodename = keyof Pick<Record<LanguageCodenames, null>, "default">;

/*
 * Typeguard for codename of 'Default project language' language
 */
export function isDefaultProjectLanguageLanguageCodename(
  value: string | undefined | null,
): value is DefaultProjectLanguageLanguageCodename {
  return typeof value === "string" && value === ("default" satisfies DefaultProjectLanguageLanguageCodename);
}
