/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.1.2'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Technical Conference
 * Environment: Production
 * Id: 39604f33-8001-00aa-4724-192a93745c77
 *
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.ts';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.ts';
import type { LanguageCodenames } from '../system/languages.generated.ts';
import type { PresentationType } from '../types/presentation.generated.ts';
import type { SpeakerType } from '../types/speaker.generated.ts';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.ts';
           
            /*
* Type representing codename of 'Agenda Session Slot' type
*/
            export type AgendaSessionSlotTypeCodename = keyof Pick<Record<TypeCodenames, null>, "agenda_session_slot">;

            /*
* Typeguard for codename of 'Agenda Session Slot' type
*/
            export function isAgendaSessionSlotTypeCodename(value: string | undefined | null): value is AgendaSessionSlotTypeCodename {
                return typeof value === 'string' && value === ('agenda_session_slot' satisfies AgendaSessionSlotTypeCodename);
            }

/*
    * Agenda Session Slot
    *
    * Id: 70b086bf-6eaf-40d9-a100-63f301901471
* Codename: agenda_session_slot
    */
export type AgendaSessionSlotType = IContentItem<
{
/*
    * Start Date/Time
    *
    * Codename: start_time
* Id: bca75ca0-0e2d-4adb-963d-5f99f308742f
* Type: date_time
* Required: true
    */
                readonly start_time: Elements.DateTimeElement;

/*
    * End Date/Time
    *
    * Codename: end_time
* Id: d9e8a177-022d-459e-9dfd-34691a0350a4
* Type: date_time
* Required: true
    */
                readonly end_time: Elements.DateTimeElement;

/*
    * Room
    *
    * Codename: room
* Id: e7e3f418-d3ae-437f-a370-a99a67ede419
* Type: text
* Required: true
    */
                readonly room: Elements.TextElement;

/*
    * Presentation
    *
    * Codename: presentation
* Id: 3567299d-d447-4004-95bd-ebea8412d225
* Type: modular_content
* Required: false
* Allowed content types: presentation
    */
                readonly presentation: Elements.LinkedItemsElement<PresentationType>;

/*
    * Assigned Speakers
    *
    * Codename: assigned_speakers
* Id: 215286e1-40d8-488b-a6ab-7c747a588d28
* Type: modular_content
* Required: false
* Allowed content types: speaker
    */
                readonly assigned_speakers: Elements.LinkedItemsElement<SpeakerType>;}, 
AgendaSessionSlotTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Agenda Session Slot
*/
export type AgendaSessionSlotTypeElementCodenames = 'start_time' | 'end_time' | 'room' | 'presentation' | 'assigned_speakers';;

/*
    * Type guard for Agenda Session Slot
    *
    * Id: 70b086bf-6eaf-40d9-a100-63f301901471
* Codename: agenda_session_slot
    */
export function isAgendaSessionSlotType(item: IContentItem | undefined | null): item is AgendaSessionSlotType {
                return item?.system.type === ('agenda_session_slot' satisfies AgendaSessionSlotTypeCodename);
            };



            