/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.1.2'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Technical Conference
 * Environment: Production
 * Id: 39604f33-8001-00aa-4724-192a93745c77
 *
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk";
import type { CollectionCodenames } from "../system/collections.generated.ts";
import type { LanguageCodenames } from "../system/languages.generated.ts";
import type { CoreType, TypeCodenames } from "../system/types.generated.ts";
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated.ts";

/*
 * Type representing codename of 'Company' type
 */
export type CompanyTypeCodename = keyof Pick<Record<TypeCodenames, null>, "company">;

/*
 * Typeguard for codename of 'Company' type
 */
export function isCompanyTypeCodename(value: string | undefined | null): value is CompanyTypeCodename {
  return typeof value === "string" && value === ("company" satisfies CompanyTypeCodename);
}

/*
 * Company
 *
 * Id: 91158911-fc76-471d-b803-df255e5be5e1
 * Codename: company
 */
export type CompanyType = IContentItem<
  {
    /*
     * Title
     *
     * Codename: title
     * Id: 82202b42-38f5-4f67-963c-9fe547b3135d
     * Type: text
     * Required: true
     */
    readonly title: Elements.TextElement;

    /*
     * Images
     *
     * Codename: images
     * Id: 8685a654-ab34-4aad-bab4-f7f1c01b655a
     * Type: asset
     * Required: false
     */
    readonly images: Elements.AssetsElement;

    /*
     * Short Bio
     *
     * Codename: short_bio
     * Id: 5c899cea-4a74-4b3c-b37a-d392fcb36b0f
     * Type: rich_text
     * Required: false
     */
    readonly short_bio: Elements.RichTextElement<CoreType>;

    /*
     * Company URL
     *
     * Codename: company_url
     * Id: b8d0d578-d65d-494b-baac-4413aa964413
     * Type: text
     * Required: true
     */
    readonly company_url: Elements.TextElement;
  },
  CompanyTypeCodename,
  LanguageCodenames,
  CollectionCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames
>;

/*
 * Type representing all available element codenames for Company
 */
export type CompanyTypeElementCodenames = "title" | "images" | "short_bio" | "company_url";

/*
 * Type guard for Company
 *
 * Id: 91158911-fc76-471d-b803-df255e5be5e1
 * Codename: company
 */
export function isCompanyType(item: IContentItem | undefined | null): item is CompanyType {
  return item?.system.type === ("company" satisfies CompanyTypeCodename);
}
