/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.1.2'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Technical Conference
 * Environment: Production
 * Id: 39604f33-8001-00aa-4724-192a93745c77
 *
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.ts';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.ts';
import type { CompanyType } from '../types/company.generated.ts';
import type { EventType } from '../types/event.generated.ts';
import type { LanguageCodenames } from '../system/languages.generated.ts';
import type { MetadataSnippet } from '../snippets/seo-social.generated.ts';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.ts';
           
            /*
* Type representing codename of 'Conference' type
*/
            export type ConferenceTypeCodename = keyof Pick<Record<TypeCodenames, null>, "conference">;

            /*
* Typeguard for codename of 'Conference' type
*/
            export function isConferenceTypeCodename(value: string | undefined | null): value is ConferenceTypeCodename {
                return typeof value === 'string' && value === ('conference' satisfies ConferenceTypeCodename);
            }

/*
    * Conference
    *
    * Id: 22434048-3e73-455b-9c3b-322877cf0d6b
* Codename: conference
    */
export type ConferenceType = IContentItem<
{
/*
    * Title
    *
    * Codename: title
* Id: c132d5ed-0c65-4ef6-8c5f-58e7c5e6d812
* Type: text
* Required: true
    */
                readonly title: Elements.TextElement;

/*
    * Images
    *
    * Codename: images
* Id: 636bd899-898e-488f-8cfe-9649e81fe8bc
* Type: asset
* Required: true
    */
                readonly images: Elements.AssetsElement;

/*
    * Sponsors
    *
    * Codename: sponsors
* Id: 752c4c48-26a1-498c-b512-edb4b39388cb
* Type: modular_content
* Required: false
* Allowed content types: company
    */
                readonly sponsors: Elements.LinkedItemsElement<CompanyType>;

/*
    * Events
    *
    * Codename: events
* Id: aac98d1d-44c3-4e5d-b91f-e2a18b5d7bff
* Type: modular_content
* Required: true
* Allowed content types: event
    */
                readonly events: Elements.LinkedItemsElement<EventType>;} & MetadataSnippet, 
ConferenceTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Conference
*/
export type ConferenceTypeElementCodenames = 'title' | 'images' | 'sponsors' | 'events' | 'seo___social__meta_title' | 'seo___social__meta_description' | 'seo___social__keywords';;

/*
    * Type guard for Conference
    *
    * Id: 22434048-3e73-455b-9c3b-322877cf0d6b
* Codename: conference
    */
export function isConferenceType(item: IContentItem | undefined | null): item is ConferenceType {
                return item?.system.type === ('conference' satisfies ConferenceTypeCodename);
            };



            