/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.1.2'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Technical Conference
 * Environment: Production
 * Id: 39604f33-8001-00aa-4724-192a93745c77
 *
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.ts';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { AgendaSessionSlotType } from '../types/agenda-session-slot.generated.ts';
import type { CollectionCodenames } from '../system/collections.generated.ts';
import type { CompanyType } from '../types/company.generated.ts';
import type { CoreType } from '../system/types.generated.ts';
import type { LanguageCodenames } from '../system/languages.generated.ts';
import type { MetadataSnippet } from '../snippets/seo-social.generated.ts';
import type { VenueType } from '../types/venue.generated.ts';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.ts';
           
            /*
* Type representing codename of 'Event' type
*/
            export type EventTypeCodename = keyof Pick<Record<TypeCodenames, null>, "event">;

            /*
* Typeguard for codename of 'Event' type
*/
            export function isEventTypeCodename(value: string | undefined | null): value is EventTypeCodename {
                return typeof value === 'string' && value === ('event' satisfies EventTypeCodename);
            }

/*
    * Event
    *
    * Id: 56f053b3-d045-47ae-a392-8740d142025f
* Codename: event
    */
export type EventType = IContentItem<
{
/*
    * Title
    *
    * Codename: title
* Id: a745c81b-0c98-40d8-9170-d3f39306b1e8
* Type: text
* Required: true
    */
                readonly title: Elements.TextElement;

/*
    * Start Date/Time
    *
    * Codename: start_and_end_date_time
* Id: 1aa2cd0e-b7cf-446d-904f-08948c1077b5
* Type: date_time
* Required: true
    */
                readonly start_and_end_date_time: Elements.DateTimeElement;

/*
    * End Date/Time
    *
    * Codename: end_date_time
* Id: aff3119c-a0b4-412d-9084-fd8bd58e7457
* Type: date_time
* Required: true
    */
                readonly end_date_time: Elements.DateTimeElement;

/*
    * Images
    *
    * Codename: images
* Id: b3566f90-59e7-4f66-9674-de10aed9ef86
* Type: asset
* Required: true
    */
                readonly images: Elements.AssetsElement;

/*
    * Venue
    *
    * Codename: venue
* Id: fa246766-1b24-450a-836b-47e4f5522ead
* Type: modular_content
* Required: true
* Allowed content types: venue
    */
                readonly venue: Elements.LinkedItemsElement<VenueType>;

/*
    * Agenda
    *
    * Codename: agenda
* Id: 367b1edc-42c2-43ba-b13a-1a8f4a301797
* Type: modular_content
* Required: true
* Allowed content types: agenda_session_slot
    */
                readonly agenda: Elements.LinkedItemsElement<AgendaSessionSlotType>;

/*
    * Sponsors
    *
    * Codename: sponsors
* Id: f638b5fb-b9d7-4a29-b3c4-ef6f17a7eea4
* Type: modular_content
* Required: true
* Allowed content types: company
    */
                readonly sponsors: Elements.LinkedItemsElement<CompanyType>;} & MetadataSnippet, 
EventTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Event
*/
export type EventTypeElementCodenames = 'title' | 'start_and_end_date_time' | 'end_date_time' | 'images' | 'venue' | 'agenda' | 'sponsors' | 'seo___social__meta_title' | 'seo___social__meta_description' | 'seo___social__keywords';;

/*
    * Type guard for Event
    *
    * Id: 56f053b3-d045-47ae-a392-8740d142025f
* Codename: event
    */
export function isEventType(item: IContentItem | undefined | null): item is EventType {
                return item?.system.type === ('event' satisfies EventTypeCodename);
            };



            