/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.1.2'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Technical Conference
 * Environment: Production
 * Id: 39604f33-8001-00aa-4724-192a93745c77
 *
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk";
import type { CollectionCodenames } from "../system/collections.generated.ts";
import type { LanguageCodenames } from "../system/languages.generated.ts";
import type { CoreType, TypeCodenames } from "../system/types.generated.ts";
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated.ts";
import type { CompanyType } from "../types/company.generated.ts";
import type { ConferenceType } from "../types/conference.generated.ts";
import type { EventType } from "../types/event.generated.ts";
import type { VenueType } from "../types/venue.generated.ts";

/*
 * Type representing codename of 'Landing Page' type
 */
export type LandingPageTypeCodename = keyof Pick<Record<TypeCodenames, null>, "landing_page">;

/*
 * Typeguard for codename of 'Landing Page' type
 */
export function isLandingPageTypeCodename(value: string | undefined | null): value is LandingPageTypeCodename {
  return typeof value === "string" && value === ("landing_page" satisfies LandingPageTypeCodename);
}

/*
 * Landing Page
 *
 * Id: db52722b-23b1-4b9a-82ae-fffc13eed4b7
 * Codename: landing_page
 */
export type LandingPageType = IContentItem<
  {
    /*
     * Headline
     *
     * Codename: headline
     * Id: cc30c762-d470-4c81-b3b3-a3971551841d
     * Type: text
     * Required: true
     */
    readonly headline: Elements.TextElement;

    /*
     * Subheadline
     *
     * Codename: subheadline
     * Id: 74007097-bb91-430c-a827-90c1593e71e7
     * Type: text
     * Required: true
     */
    readonly subheadline: Elements.TextElement;

    /*
     * Hero Image
     *
     * Codename: hero_image
     * Id: c578b5d2-0604-4e11-845c-b789546c95ec
     * Type: asset
     * Required: true
     */
    readonly hero_image: Elements.AssetsElement;

    /*
     * Body Copy
     *
     * Codename: body_copy
     * Id: 3c41ef3f-bbb8-42e4-b637-d2bb39128202
     * Type: rich_text
     * Required: false
     */
    readonly body_copy: Elements.RichTextElement<CoreType>;

    /*
     * Featured Content
     *
     * Codename: featured_content
     * Id: a0323f40-29be-4801-9fcf-6725d7a6a254
     * Type: modular_content
     * Required: false
     * Allowed content types: venue, event, conference, company
     */
    readonly featured_content: Elements.LinkedItemsElement<VenueType | EventType | ConferenceType | CompanyType>;

    /*
     * Featured Content
     *
     * Codename: featured_content_a57b567
     * Id: a57b5678-acfd-4276-8967-8b6de23f98f1
     * Type: rich_text
     * Required: false
     * Guidelines: Carousel Element
     */
    readonly featured_content_a57b567: Elements.RichTextElement<CoreType>;

    /*
     * Carousel
     *
     * Codename: carousel
     * Id: d3dedd80-b91d-513f-99df-fd3de3318eee
     * Type: multiple_choice
     * Required: false
     * Options: automatic, manual
     */
    readonly carousel: Elements.MultipleChoiceElement;

    /*
     * URL Slug
     *
     * Codename: url_slug
     * Id: 7a67821c-a330-44fe-a92e-519d0f74aa21
     * Type: url_slug
     * Required: true
     */
    readonly url_slug: Elements.UrlSlugElement;

    /*
     * Untitled subpages
     *
     * Codename: untitled_subpages
     * Id: 7e4958ab-d4b6-4218-8615-65e2f9007dbf
     * Type: subpages
     * Required: false
     */
    readonly untitled_subpages: Elements.LinkedItemsElement<CoreType>;
  },
  LandingPageTypeCodename,
  LanguageCodenames,
  CollectionCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames
>;

/*
 * Type representing all available element codenames for Landing Page
 */
export type LandingPageTypeElementCodenames =
  | "headline"
  | "subheadline"
  | "hero_image"
  | "body_copy"
  | "featured_content"
  | "featured_content_a57b567"
  | "carousel"
  | "url_slug"
  | "untitled_subpages";

/*
 * Type guard for Landing Page
 *
 * Id: db52722b-23b1-4b9a-82ae-fffc13eed4b7
 * Codename: landing_page
 */
export function isLandingPageType(item: IContentItem | undefined | null): item is LandingPageType {
  return item?.system.type === ("landing_page" satisfies LandingPageTypeCodename);
}
