/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.1.2'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Technical Conference
 * Environment: Production
 * Id: 39604f33-8001-00aa-4724-192a93745c77
 *
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk";
import type { MetadataSnippet } from "../snippets/seo-social.generated.ts";
import type { CollectionCodenames } from "../system/collections.generated.ts";
import type { LanguageCodenames } from "../system/languages.generated.ts";
import type { CoreType, TypeCodenames } from "../system/types.generated.ts";
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated.ts";
import type { AgendaSessionSlotType } from "../types/agenda-session-slot.generated.ts";
import type { CompanyType } from "../types/company.generated.ts";
import type { ConferenceType } from "../types/conference.generated.ts";
import type { EventType } from "../types/event.generated.ts";
import type { PresentationType } from "../types/presentation.generated.ts";
import type { SpeakerType } from "../types/speaker.generated.ts";
import type { VenueType } from "../types/venue.generated.ts";

/*
 * Type representing codename of 'Page' type
 */
export type PageTypeCodename = keyof Pick<Record<TypeCodenames, null>, "page">;

/*
 * Typeguard for codename of 'Page' type
 */
export function isPageTypeCodename(value: string | undefined | null): value is PageTypeCodename {
  return typeof value === "string" && value === ("page" satisfies PageTypeCodename);
}

/*
 * Page
 *
 * Id: 8d7ba40a-3cfd-4ddf-a4f2-561cf7cd85fb
 * Codename: page
 */
export type PageType = IContentItem<
  {
    /*
     * Headline
     *
     * Codename: headline
     * Id: 442d0bd4-128c-5653-befe-ee105e927a7f
     * External Id: page_el_headline
     * Type: text
     * Required: true
     */
    readonly headline: Elements.TextElement;

    /*
     * Subheadline
     *
     * Codename: subheadline
     * Id: 0dfb1283-f5d8-5b03-8990-5ea2bec8d10d
     * External Id: page_el_subheadline
     * Type: text
     * Required: true
     */
    readonly subheadline: Elements.TextElement;

    /*
     * Body Copy
     *
     * Codename: body_copy
     * Id: 28e34c45-d4f1-551d-abcf-b7c1dfa22e1b
     * External Id: page_el_body_copy
     * Type: rich_text
     * Required: false
     */
    readonly body_copy: Elements.RichTextElement<CoreType>;

    /*
     * Featured Content
     *
     * Codename: featured_content
     * Id: 4922f6f8-1593-56f5-8af3-13ed0331a17f
     * External Id: page_el_featured_content
     * Type: modular_content
     * Required: false
     * Allowed content types: venue, event, conference, company, agenda_session_slot, presentation, speaker
     */
    readonly featured_content: Elements.LinkedItemsElement<
      VenueType | EventType | ConferenceType | CompanyType | AgendaSessionSlotType | PresentationType | SpeakerType
    >;

    /*
     * Sponsors
     *
     * Codename: sponsors
     * Id: bfe7d637-e6ba-4721-95bc-51dd50cf0f72
     * Type: modular_content
     * Required: false
     * Allowed content types: company
     */
    readonly sponsors: Elements.LinkedItemsElement<CompanyType>;
  } & MetadataSnippet,
  PageTypeCodename,
  LanguageCodenames,
  CollectionCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames
>;

/*
 * Type representing all available element codenames for Page
 */
export type PageTypeElementCodenames =
  | "headline"
  | "subheadline"
  | "body_copy"
  | "featured_content"
  | "sponsors"
  | "seo___social__meta_title"
  | "seo___social__meta_description"
  | "seo___social__keywords";

/*
 * Type guard for Page
 *
 * Id: 8d7ba40a-3cfd-4ddf-a4f2-561cf7cd85fb
 * Codename: page
 */
export function isPageType(item: IContentItem | undefined | null): item is PageType {
  return item?.system.type === ("page" satisfies PageTypeCodename);
}
