/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.1.2'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Technical Conference
 * Environment: Production
 * Id: 39604f33-8001-00aa-4724-192a93745c77
 *
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk";
import type { CollectionCodenames } from "../system/collections.generated.ts";
import type { LanguageCodenames } from "../system/languages.generated.ts";
import type { CoreType, TypeCodenames } from "../system/types.generated.ts";
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated.ts";
import type { TopicsTaxonomyCodename, TopicsTaxonomyTermCodenames } from "../taxonomies/topic.generated.ts";

/*
 * Type representing codename of 'Presentation' type
 */
export type PresentationTypeCodename = keyof Pick<Record<TypeCodenames, null>, "presentation">;

/*
 * Typeguard for codename of 'Presentation' type
 */
export function isPresentationTypeCodename(value: string | undefined | null): value is PresentationTypeCodename {
  return typeof value === "string" && value === ("presentation" satisfies PresentationTypeCodename);
}

/*
 * Presentation
 *
 * Id: 135723b1-c454-4189-ab0e-9b9389ba1ac6
 * Codename: presentation
 */
export type PresentationType = IContentItem<
  {
    /*
     * Title
     *
     * Codename: title
     * Id: e22ce6a0-71d1-4c69-b834-5cabc05a80cd
     * Type: text
     * Required: true
     */
    readonly title: Elements.TextElement;

    /*
     * Summary
     *
     * Codename: summary
     * Id: 90d1847f-71f0-433f-a3c0-5edb669ee7f4
     * Type: rich_text
     * Required: true
     */
    readonly summary: Elements.RichTextElement<CoreType>;

    /*
     * Topics
     *
     * Codename: topic
     * Id: a9f315d8-fc43-436b-a3c1-588b5f0dc7fd
     * Type: taxonomy
     * Required: true
     * Taxonomy: topic
     */
    readonly topic: Elements.TaxonomyElement<TopicsTaxonomyTermCodenames, TopicsTaxonomyCodename>;

    /*
     * Slides/Downloads
     *
     * Codename: slides_downloads
     * Id: 20c9fecf-f503-4ad9-9806-3a78a76f6c16
     * Type: asset
     * Required: false
     */
    readonly slides_downloads: Elements.AssetsElement;
  },
  PresentationTypeCodename,
  LanguageCodenames,
  CollectionCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames
>;

/*
 * Type representing all available element codenames for Presentation
 */
export type PresentationTypeElementCodenames = "title" | "summary" | "topic" | "slides_downloads";

/*
 * Type guard for Presentation
 *
 * Id: 135723b1-c454-4189-ab0e-9b9389ba1ac6
 * Codename: presentation
 */
export function isPresentationType(item: IContentItem | undefined | null): item is PresentationType {
  return item?.system.type === ("presentation" satisfies PresentationTypeCodename);
}
