/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.1.2'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Technical Conference
 * Environment: Production
 * Id: 39604f33-8001-00aa-4724-192a93745c77
 *
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk";
import type { CollectionCodenames } from "../system/collections.generated.ts";
import type { LanguageCodenames } from "../system/languages.generated.ts";
import type { CoreType, TypeCodenames } from "../system/types.generated.ts";
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated.ts";
import type { CompanyType } from "../types/company.generated.ts";

/*
 * Type representing codename of 'Speaker' type
 */
export type SpeakerTypeCodename = keyof Pick<Record<TypeCodenames, null>, "speaker">;

/*
 * Typeguard for codename of 'Speaker' type
 */
export function isSpeakerTypeCodename(value: string | undefined | null): value is SpeakerTypeCodename {
  return typeof value === "string" && value === ("speaker" satisfies SpeakerTypeCodename);
}

/*
 * Speaker
 *
 * Id: 1dd26b7e-ae99-494a-9938-b237b7ca2d54
 * Codename: speaker
 */
export type SpeakerType = IContentItem<
  {
    /*
     * Name
     *
     * Codename: name
     * Id: dc000cfb-85a7-4516-aa53-6ec7a6675a17
     * Type: text
     * Required: true
     */
    readonly name: Elements.TextElement;

    /*
     * Title
     *
     * Codename: title
     * Id: e00837fa-5072-4812-acd1-bbcc1dacb2e1
     * Type: text
     * Required: true
     */
    readonly title: Elements.TextElement;

    /*
     * Biography
     *
     * Codename: biography
     * Id: b3ae07ad-d9db-4e9d-b251-2e89019d7d04
     * Type: rich_text
     * Required: true
     */
    readonly biography: Elements.RichTextElement<CoreType>;

    /*
     * Company
     *
     * Codename: company
     * Id: 2da5732e-8676-4124-bf4e-5e286024270f
     * Type: modular_content
     * Required: true
     * Allowed content types: company
     */
    readonly company: Elements.LinkedItemsElement<CompanyType>;

    /*
     * Photo
     *
     * Codename: photo
     * Id: f6c43b4b-6d23-465b-b2ee-6d2bf2d3e07b
     * Type: asset
     * Required: true
     */
    readonly photo: Elements.AssetsElement;

    /*
     * LinkedIn URL
     *
     * Codename: linkedin
     * Id: 0e8a59b0-6a9d-4786-a408-7c1dae44b7f9
     * Type: text
     * Required: true
     */
    readonly linkedin: Elements.TextElement;

    /*
     * Website
     *
     * Codename: website
     * Id: d9ac8615-ff82-492b-86bc-f45c979696b0
     * Type: text
     * Required: false
     */
    readonly website: Elements.TextElement;

    /*
     * Email
     *
     * Codename: email
     * Id: 16bf092e-9433-46ea-9f82-933d9268eb0c
     * Type: text
     * Required: false
     */
    readonly email: Elements.TextElement;
  },
  SpeakerTypeCodename,
  LanguageCodenames,
  CollectionCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames
>;

/*
 * Type representing all available element codenames for Speaker
 */
export type SpeakerTypeElementCodenames =
  | "name"
  | "title"
  | "biography"
  | "company"
  | "photo"
  | "linkedin"
  | "website"
  | "email";

/*
 * Type guard for Speaker
 *
 * Id: 1dd26b7e-ae99-494a-9938-b237b7ca2d54
 * Codename: speaker
 */
export function isSpeakerType(item: IContentItem | undefined | null): item is SpeakerType {
  return item?.system.type === ("speaker" satisfies SpeakerTypeCodename);
}
