/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.1.2'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Technical Conference
 * Environment: Production
 * Id: 39604f33-8001-00aa-4724-192a93745c77
 *
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk";
import type { MetadataSnippet } from "../snippets/seo-social.generated.ts";
import type { CollectionCodenames } from "../system/collections.generated.ts";
import type { LanguageCodenames } from "../system/languages.generated.ts";
import type { CoreType, TypeCodenames } from "../system/types.generated.ts";
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated.ts";

/*
 * Type representing codename of 'Venue' type
 */
export type VenueTypeCodename = keyof Pick<Record<TypeCodenames, null>, "venue">;

/*
 * Typeguard for codename of 'Venue' type
 */
export function isVenueTypeCodename(value: string | undefined | null): value is VenueTypeCodename {
  return typeof value === "string" && value === ("venue" satisfies VenueTypeCodename);
}

/*
 * Venue
 *
 * Id: 8f364a89-c617-4bfa-8b78-f3ee6103efe1
 * Codename: venue
 */
export type VenueType = IContentItem<
  {
    /*
     * Name
     *
     * Codename: name
     * Id: 38d46cf8-9801-4fd0-a256-905f044fbc54
     * Type: text
     * Required: true
     */
    readonly name: Elements.TextElement;

    /*
     * Location
     *
     * Codename: location
     * Id: 05c0908f-6c31-4b98-9325-60f323cf812d
     * Type: text
     * Required: true
     */
    readonly location: Elements.TextElement;

    /*
     * Website
     *
     * Codename: website
     * Id: a54b49a5-d185-4824-b1bb-6f9af8c7aea3
     * Type: text
     * Required: false
     */
    readonly website: Elements.TextElement;

    /*
     * Images
     *
     * Codename: images
     * Id: f55cfba1-6bcd-413f-86ce-adf895d23e8e
     * Type: asset
     * Required: false
     */
    readonly images: Elements.AssetsElement;

    /*
     * Directions
     *
     * Codename: directions
     * Id: e324e5e6-93f6-41b2-a992-8332edc2ebca
     * Type: rich_text
     * Required: false
     */
    readonly directions: Elements.RichTextElement<CoreType>;

    /*
     * Parking
     *
     * Codename: parking
     * Id: 2f6107e9-0b48-4012-a78c-3fc3b88696c1
     * Type: rich_text
     * Required: false
     */
    readonly parking: Elements.RichTextElement<CoreType>;
  } & MetadataSnippet,
  VenueTypeCodename,
  LanguageCodenames,
  CollectionCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames
>;

/*
 * Type representing all available element codenames for Venue
 */
export type VenueTypeElementCodenames =
  | "name"
  | "location"
  | "website"
  | "images"
  | "directions"
  | "parking"
  | "seo___social__meta_title"
  | "seo___social__meta_description"
  | "seo___social__keywords";

/*
 * Type guard for Venue
 *
 * Id: 8f364a89-c617-4bfa-8b78-f3ee6103efe1
 * Codename: venue
 */
export function isVenueType(item: IContentItem | undefined | null): item is VenueType {
  return item?.system.type === ("venue" satisfies VenueTypeCodename);
}
