/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.1.2'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Technical Conference
 * Environment: Production
 * Id: 39604f33-8001-00aa-4724-192a93745c77
 *
 * -------------------------------------------------------------------------------
 */

import type { WorkflowCodenames } from "../system/workflows.generated.ts";

/*
 * Type representing codename of 'Marketing Content' workflow
 */
export type MarketingContentWorkflowCodename = keyof Pick<Record<WorkflowCodenames, null>, "default">;

/*
 * Typeguard for codename of 'Marketing Content' workflow
 */
export function isMarketingContentWorkflowCodename(
  value: string | undefined | null,
): value is MarketingContentWorkflowCodename {
  return typeof value === "string" && value === ("default" satisfies MarketingContentWorkflowCodename);
}

/*
 * Array of all workflow step codenames
 */
export const marketingContentWorkflowStepCodenames = [
  "draft",
  "seo_geo_review",
  "marketing_review",
  "legal_review",
  "final_review",
  "published",
  "archived",
  "scheduled",
] as const;

/*
 * Type representing all workflow step codenames
 */
export type MarketingContentWorkflowStepCodenames = (typeof marketingContentWorkflowStepCodenames)[number];

/*
 * Typeguard for workflow step codename
 */
export function isMarketingContentWorkflowStepCodename(
  value: string | undefined | null,
): value is MarketingContentWorkflowStepCodenames {
  return typeof value === "string" && (marketingContentWorkflowStepCodenames as readonly string[]).includes(value);
}
