/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.1.2'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Technical Conference
 * Environment: Production
 * Id: 39604f33-8001-00aa-4724-192a93745c77
 *
 * -------------------------------------------------------------------------------
 */

import type { WorkflowCodenames } from "../system/workflows.generated.ts";

/*
 * Type representing codename of 'Presentation Content' workflow
 */
export type PresentationContentWorkflowCodename = keyof Pick<Record<WorkflowCodenames, null>, "presentation_content">;

/*
 * Typeguard for codename of 'Presentation Content' workflow
 */
export function isPresentationContentWorkflowCodename(
  value: string | undefined | null,
): value is PresentationContentWorkflowCodename {
  return typeof value === "string" && value === ("presentation_content" satisfies PresentationContentWorkflowCodename);
}

/*
 * Array of all workflow step codenames
 */
export const presentationContentWorkflowStepCodenames = [
  "draft_39cecae",
  "published",
  "archived",
  "scheduled",
] as const;

/*
 * Type representing all workflow step codenames
 */
export type PresentationContentWorkflowStepCodenames = (typeof presentationContentWorkflowStepCodenames)[number];

/*
 * Typeguard for workflow step codename
 */
export function isPresentationContentWorkflowStepCodename(
  value: string | undefined | null,
): value is PresentationContentWorkflowStepCodenames {
  return typeof value === "string" && (presentationContentWorkflowStepCodenames as readonly string[]).includes(value);
}
