/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.1.2'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Technical Conference
 * Environment: Production
 * Id: 39604f33-8001-00aa-4724-192a93745c77
 *
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all element codenames
 */
export const elementCodenames = [
  "title",
  "images",
  "short_bio",
  "company_url",
  "summary",
  "topic",
  "slides_downloads",
  "website",
  "name",
  "biography",
  "company",
  "photo",
  "linkedin",
  "email",
  "location",
  "directions",
  "parking",
  "seo___social__meta_title",
  "seo___social__meta_description",
  "seo___social__keywords",
  "start_time",
  "end_time",
  "room",
  "presentation",
  "assigned_speakers",
  "region",
  "start_and_end_date_time",
  "end_date_time",
  "venue",
  "agenda",
  "sponsors",
  "events",
  "headline",
  "subheadline",
  "hero_image",
  "body_copy",
  "featured_content",
  "url_slug",
  "untitled_subpages",
] as const;

/*
 * Type representing all element codenames
 */
export type ElementCodenames = (typeof elementCodenames)[number];

/*
 * Typeguard for element codename
 */
export function isElementCodename(value: string | undefined | null): value is ElementCodenames {
  return typeof value === "string" && (elementCodenames as readonly string[]).includes(value);
}
