/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.1.2'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Technical Conference
 * Environment: Production
 * Id: 39604f33-8001-00aa-4724-192a93745c77
 *
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all taxonomy codenames
 */
export const taxonomyCodenames = ["region", "topic", "sponsor"] as const;

/*
 * Type representing all taxonomy codenames
 */
export type TaxonomyCodenames = (typeof taxonomyCodenames)[number];

/*
 * Typeguard for taxonomy codename
 */
export function isTaxonomyCodename(value: string | undefined | null): value is TaxonomyCodenames {
  return typeof value === "string" && (taxonomyCodenames as readonly string[]).includes(value);
}
