/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.1.2'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Technical Conference
 * Environment: Production
 * Id: 39604f33-8001-00aa-4724-192a93745c77
 *
 * -------------------------------------------------------------------------------
 */

import type { AgendaSessionSlotType } from "../types/agenda-session-slot.generated.ts";
import type { CompanyType } from "../types/company.generated.ts";
import type { ConferenceType } from "../types/conference.generated.ts";
import type { EventType } from "../types/event.generated.ts";
import type { LandingPageType } from "../types/landing-page.generated.ts";
import type { PresentationType } from "../types/presentation.generated.ts";
import type { SpeakerType } from "../types/speaker.generated.ts";
import type { VenueType } from "../types/venue.generated.ts";

/*
 * Array of all type codenames
 */
export const typeCodenames = [
  "company",
  "presentation",
  "speaker",
  "venue",
  "agenda_session_slot",
  "event",
  "conference",
  "landing_page",
] as const;

/*
 * Type representing all type codenames
 */
export type TypeCodenames = (typeof typeCodenames)[number];

/*
 * Typeguard for type codename
 */
export function isTypeCodename(value: string | undefined | null): value is TypeCodenames {
  return typeof value === "string" && (typeCodenames as readonly string[]).includes(value);
}

/*
 * Core content type with narrowed types. Use this instead of'IContentItem' for increased type safety.
 */
export type CoreType =
  | CompanyType
  | PresentationType
  | SpeakerType
  | VenueType
  | AgendaSessionSlotType
  | EventType
  | ConferenceType
  | LandingPageType;

/*
 * Type mapping for codename & type. Can be used for type safe access to type based on the codename of type.
 */
export type CodenameTypeMapping = {
  readonly company: CompanyType;
  readonly presentation: PresentationType;
  readonly speaker: SpeakerType;
  readonly venue: VenueType;
  readonly agenda_session_slot: AgendaSessionSlotType;
  readonly event: EventType;
  readonly conference: ConferenceType;
  readonly landing_page: LandingPageType;
};

/*
 * Helper type that returns type based on the codename of type.
 */
export type CodenameTypeMapper<TTypeCodename extends TypeCodenames> = TTypeCodename extends keyof CodenameTypeMapping
  ? CodenameTypeMapping[TTypeCodename]
  : CoreType;
