/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.1.2'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Technical Conference
 * Environment: Production
 * Id: 39604f33-8001-00aa-4724-192a93745c77
 *
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all workflow codenames
 */
export const workflowCodenames = ["default", "presentation_content"] as const;

/*
 * Type representing all workflow codenames
 */
export type WorkflowCodenames = (typeof workflowCodenames)[number];

/*
 * Typeguard for workflow codename
 */
export function isWorkflowCodename(value: string | undefined | null): value is WorkflowCodenames {
  return typeof value === "string" && (workflowCodenames as readonly string[]).includes(value);
}

/*
 * Array of all workflow codenames
 */
export const workflowStepCodenames = [
  "draft",
  "seo_geo_review",
  "marketing_review",
  "published",
  "archived",
  "scheduled",
  "draft_39cecae",
] as const;

/*
 * Type representing all workflow codenames
 */
export type WorkflowStepCodenames = (typeof workflowStepCodenames)[number];

/*
 * Typeguard for workflow codename
 */
export function isWorkflowStepCodename(value: string | undefined | null): value is WorkflowStepCodenames {
  return typeof value === "string" && (workflowStepCodenames as readonly string[]).includes(value);
}
