/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.1.2'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Technical Conference
 * Environment: Production
 * Id: 39604f33-8001-00aa-4724-192a93745c77
 *
 * -------------------------------------------------------------------------------
 */

import type { TaxonomyCodenames } from "../system/taxonomies.generated.ts";

/*
 * Type representing codename of 'Region' taxonomy
 */
export type RegionTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "region">;

/*
 * Typeguard for codename of 'Region' taxonomy
 */
export function isRegionTaxonomyCodename(value: string | undefined | null): value is RegionTaxonomyCodename {
  return typeof value === "string" && value === ("region" satisfies RegionTaxonomyCodename);
}

/*
 * Array of all taxonomy term codenames
 */
export const regionTaxonomyTermCodenames = ["united_states", "europe"] as const;

/*
 * Type representing all taxonomy term codenames
 */
export type RegionTaxonomyTermCodenames = (typeof regionTaxonomyTermCodenames)[number];

/*
 * Typeguard for taxonomy term codename
 */
export function isRegionTaxonomyTermCodename(value: string | undefined | null): value is RegionTaxonomyTermCodenames {
  return typeof value === "string" && (regionTaxonomyTermCodenames as readonly string[]).includes(value);
}
