/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.1.2'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Technical Conference
 * Environment: Production
 * Id: 39604f33-8001-00aa-4724-192a93745c77
 *
 * -------------------------------------------------------------------------------
 */

import type { TaxonomyCodenames } from "../system/taxonomies.generated.ts";

/*
 * Type representing codename of 'Sponsor' taxonomy
 */
export type SponsorTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "sponsor">;

/*
 * Typeguard for codename of 'Sponsor' taxonomy
 */
export function isSponsorTaxonomyCodename(value: string | undefined | null): value is SponsorTaxonomyCodename {
  return typeof value === "string" && value === ("sponsor" satisfies SponsorTaxonomyCodename);
}

/*
 * Array of all taxonomy term codenames
 */
export const sponsorTaxonomyTermCodenames = ["global", "local"] as const;

/*
 * Type representing all taxonomy term codenames
 */
export type SponsorTaxonomyTermCodenames = (typeof sponsorTaxonomyTermCodenames)[number];

/*
 * Typeguard for taxonomy term codename
 */
export function isSponsorTaxonomyTermCodename(value: string | undefined | null): value is SponsorTaxonomyTermCodenames {
  return typeof value === "string" && (sponsorTaxonomyTermCodenames as readonly string[]).includes(value);
}
