/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.1.2'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Technical Conference
 * Environment: Production
 * Id: 39604f33-8001-00aa-4724-192a93745c77
 *
 * -------------------------------------------------------------------------------
 */

import type { TaxonomyCodenames } from "../system/taxonomies.generated.ts";

/*
 * Type representing codename of 'Topics' taxonomy
 */
export type TopicsTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "topic">;

/*
 * Typeguard for codename of 'Topics' taxonomy
 */
export function isTopicsTaxonomyCodename(value: string | undefined | null): value is TopicsTaxonomyCodename {
  return typeof value === "string" && value === ("topic" satisfies TopicsTaxonomyCodename);
}

/*
 * Array of all taxonomy term codenames
 */
export const topicsTaxonomyTermCodenames = [
  "cybersecurity",
  "ai_agents",
  "ai_governance",
  "ai_engineering_with_claude_code",
] as const;

/*
 * Type representing all taxonomy term codenames
 */
export type TopicsTaxonomyTermCodenames = (typeof topicsTaxonomyTermCodenames)[number];

/*
 * Typeguard for taxonomy term codename
 */
export function isTopicsTaxonomyTermCodename(value: string | undefined | null): value is TopicsTaxonomyTermCodenames {
  return typeof value === "string" && (topicsTaxonomyTermCodenames as readonly string[]).includes(value);
}
