/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.1.2'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Technical Conference
 * Environment: Production
 * Id: 39604f33-8001-00aa-4724-192a93745c77
 *
 * -------------------------------------------------------------------------------
 */

import type { CollectionCodenames } from "../system/collections.generated.ts";

/*
 * Type representing codename of 'Agenda Resources' collection
 */
export type AgendaResourcesCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "presentation_resources">;

/*
 * Typeguard for codename of 'Agenda Resources' collection
 */
export function isAgendaResourcesCollectionCodename(
  value: string | undefined | null,
): value is AgendaResourcesCollectionCodename {
  return typeof value === "string" && value === ("presentation_resources" satisfies AgendaResourcesCollectionCodename);
}
