/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.1.2'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Technical Conference
 * Environment: Production
 * Id: 39604f33-8001-00aa-4724-192a93745c77
 *
 * -------------------------------------------------------------------------------
 */

import type { CollectionCodenames } from "../system/collections.generated.ts";

/*
 * Type representing codename of 'Sponsors' collection
 */
export type SponsorsCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "sponsorship">;

/*
 * Typeguard for codename of 'Sponsors' collection
 */
export function isSponsorsCollectionCodename(value: string | undefined | null): value is SponsorsCollectionCodename {
  return typeof value === "string" && value === ("sponsorship" satisfies SponsorsCollectionCodename);
}
