/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.1.2'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Technical Conference
 * Environment: Production
 * Id: 39604f33-8001-00aa-4724-192a93745c77
 *
 * -------------------------------------------------------------------------------
 */

import type { Elements, Snippet } from "@kontent-ai/delivery-sdk";
import type { SnippetCodenames } from "../system/snippets.generated.ts";
import type { CoreType } from "../system/types.generated.ts";

/*
 * Type representing codename of 'Metadata' snippet
 */
export type MetadataSnippetCodename = keyof Pick<Record<SnippetCodenames, null>, "seo___social">;

/*
 * Typeguard for codename of 'Metadata' snippet
 */
export function isMetadataSnippetCodename(value: string | undefined | null): value is MetadataSnippetCodename {
  return typeof value === "string" && value === ("seo___social" satisfies MetadataSnippetCodename);
}

/*
 * Metadata
 *
 * Id: cb193a96-fd49-48f4-83d7-590cfaa9efd1
 * Codename: seo___social
 */
export type MetadataSnippet = Snippet<
  MetadataSnippetElementCodenames,
  {
    /*
     * Meta Title
     *
     * Codename: seo___social__meta_title
     * Id: c7eea10b-3a65-4592-9f4a-84e190d45ff1
     * Type: text
     * Required: true
     */
    readonly seo___social__meta_title: Elements.TextElement;

    /*
     * Description
     *
     * Codename: seo___social__meta_description
     * Id: 2ca1fb22-a327-4b2b-ad5a-3906c67f70e4
     * Type: rich_text
     * Required: true
     */
    readonly seo___social__meta_description: Elements.RichTextElement<CoreType>;

    /*
     * Keywords
     *
     * Codename: seo___social__keywords
     * Id: affeb32a-d79f-4b6c-b17a-ee0cd051398f
     * Type: text
     * Required: true
     */
    readonly seo___social__keywords: Elements.TextElement;
  }
>;

/*
 * Type representing all available element codenames for Metadata
 */
export type MetadataSnippetElementCodenames =
  | "seo___social__meta_title"
  | "seo___social__meta_description"
  | "seo___social__keywords";
